name: syncslides
description: A simple multi-device presentation system built on Flutter and Syncbase.
dependencies:
  flutter:
    path: "../../../../../flutter/packages/flutter"
  logging: ">=0.11.2 <0.12.0"
  mojo_services: ">=0.4.5 <0.5.0"
  syncbase: ">=0.0.27 <0.1.0"
  v23discovery: ">=0.0.10 < 0.1.0"
  uuid: ">=0.5.0 <0.6.0"
dev_dependencies:
  flutter_tools:
    path: "../../../../../flutter/packages/flutter_tools"
